"""
RNAOS unified AI intelligence profile.
"""

from __future__ import annotations

from dataclasses import dataclass

from ai.models.explanation_profile import (
    ExplanationProfile,
)
from ai.models.feature_vector import (
    FeatureVector,
)
from ai.models.knowledge_graph import (
    KnowledgeGraph,
)
from ai.models.meta_feature_profile import (
    MetaFeatureProfile,
)
from ai.models.rna_embedding import (
    RNAEmbedding,
)
from ai.models.solver_recommendation_features import (
    SolverRecommendationFeatures,
)


@dataclass(slots=True, frozen=True)
class AIIntelligenceProfile:
    """
    Unified AI intelligence profile.

    Aggregates every AI representation generated by the
    AI Intelligence Layer into a single immutable object.
    """

    feature_vector: FeatureVector

    embedding: RNAEmbedding

    knowledge_graph: KnowledgeGraph

    meta_features: MetaFeatureProfile

    solver_recommendation: SolverRecommendationFeatures

    explanation: ExplanationProfile

    @property
    def component_count(
        self,
    ) -> int:
        """
        Number of AI intelligence components.
        """
        return 6
